#pragma once
#include <cactus_side_img.h>
#include <cactus_side_small_img.h>
#include <dandelion_img.h>
#include <dandelion_small_img.h>
#include <dead_bush_img.h>
#include <dead_bush_small_img.h>
#include <dirt_img.h>
#include <dirt_small_img.h>
#include <door_img.h>
#include <door_small_img.h>
#include <grass_img.h>
#include <grass_small_img.h>
#include <inventory_slot_img.h>
#include <inventory_slot_select_img.h>
#include <oak_leaves_img.h>
#include <oak_leaves_small_img.h>
#include <oak_log_img.h>
#include <oak_log_small_img.h>
#include <planks_img.h>
#include <planks_small_img.h>
#include <poppy_img.h>
#include <poppy_small_img.h>
#include <sand_img.h>
#include <sand_small_img.h>
#include <sandstone_img.h>
#include <sandstone_small_img.h>
#include <stick_small_img.h>
#include <stone_img.h>
#include <stone_small_img.h>